
github_provider: "GitHub Provider" { style: { fill: LightSalmon } }
jira_provider: "Jira Provider" { style: { fill: LightSalmon } }
gitlab_provider: "GitLab Provider" { style: { fill: LightSalmon } }

harvester: "Harvester" { style: { fill: Khaki } }
harvester -> event_log: "appends data"
harvester <- github_provider: "harvests data"
harvester <- jira_provider: "harvests data"
harvester <- gitlab_provider: "harvests data"

event_log: "Append Only Log" { style: { fill: Khaki } }

search_index: "Search Index" { style: { fill: Khaki } }
search_index <- event_log: "reads from"

edit_ui: "Edit UI"  { style: { fill: SkyBlue } }
edit_ui -> event_log: "appends data"

discovery_ui: "Discovery UI" { style: { fill: SkyBlue } }
discovery_ui <- search_index: "queries from"

user: "User" { style: { fill: LightGreen } }
user -> discovery_ui: "interacts with" { style: { stroke-dash: 3 } }
user -> edit_ui: "interacts with" { style: { stroke-dash: 3 } }
