product: "Product"

repository: "Repository"
repository -- taxonomy
repository -- product

location: "Location [ protocol://domain:port ]"
location -- taxonomy
location -- product

taxonomy: "Taxonomy"
taxonomy -- product

kubernetes_cluster: "Kubernetes Cluster"
kubernetes_deployment: "Kubernetes Deployment"
kubernetes_namespace: "Kubernetes Namespace"

kubernetes_deployment -- kubernetes_namespace
kubernetes_namespace -- kubernetes_cluster

kubernetes_deployment -- product
kubernetes_namespace -- product
kubernetes_cluster -- product
