browser: "Web Browser"
browser.accretion
browser.accretion.css
browser.accretion.js
browser.accretion.html
browser.accretion.svg

browser.accretion -> server.accretion

server: "Server"
server.accretion
server.accretion.go

server.accretion -> server.event_store

server.accretion -> gitlab
server.accretion -> github
server.accretion -> jira
server.accretion -> confluence
server.accretion -> kubernetes
