name: "ci"

on:
  pull_request:
    branches:
      - "main"
  push:
    branches:
      - "main"

permissions: "read-all"

env:
  CGO_ENABLED: 0

jobs:
  ci:
    runs-on: "ubuntu-latest"

    steps:
      - uses: "actions/checkout@v4.2.2"
      - uses: "actions/setup-go@v5.4.0"
        with: { go-version-file: "./go.mod" }
      - uses: "golangci/golangci-lint-action@v7.0.0"
        with: { version: "latest" }
      - name: "lint"
        run: "make lint"
      - name: "test"
        run: "make test"
      - name: "build"
        uses: "goreleaser/goreleaser-action@v6.3.0"
        with: { version: "latest", args: "build --clean --snapshot" }
