name: "ci"

on:
  pull_request:
    branches:
      - "main"
  push:
    branches:
      - "main"

permissions: "read-all"

jobs:
  linux:
    runs-on: "ubuntu-latest"

    steps:
      - uses: "actions/checkout@v4.2.1"
      - uses: "actions/setup-go@v5.0.2"
        with: { go-version-file: "./go.mod" }
      - uses: "golangci/golangci-lint-action@v6.1.1"
        with: { version: "latest" }
      - name: "lint"
        run: "make lint"
      - name: "test"
        run: "make test"
      - name: "build"
        uses: "goreleaser/goreleaser-action@v6.0.0"
        with:
          version: "latest"
          args: "build --clean --snapshot"
