name: "release"

on:
  push:
    tags:
      - "*"

permissions: "read-all"

env:
  CGO_ENABLED: 0

jobs:
  release:
    runs-on: "ubuntu-latest"

    permissions:
      contents: "write"

    steps:
      - uses: "actions/checkout@v4.2.2"
      - uses: "actions/setup-go@v5.4.0"
        with: { go-version-file: "./go.mod" }
      - uses: "golangci/golangci-lint-action@v7.0.0"
        with: { version: "latest" }
      - name: "release"
        uses: "goreleaser/goreleaser-action@v6.1.0"
        with: { version: "latest", args: "release --clean" }
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          HOMEBREW_TAP_GITHUB_TOKEN: ${{ secrets.HOMEBREW_TAP_GITHUB_TOKEN }}
